### ISSUE TITLE
Couldnt make mod work

### ISSUE THREAD

**Issue by oskurd** [nathanhinchey/NobleFates-AdvancedBarracks#1]
Hi!

I create Mods folder with capital letter, dropped first those 2 room and building files into folder and launched game, used old save file and new save but couldnt see new building or room on list page. I tried add every folder, license and read me files as well and still same issue. So what went wrong? i think atleast i followed instructions as were told

**Comment by nathanhinchey** [comment]
the files need to be in a subfolder within the Mods folder. For instance `C:\Users\oskurd\AppData\LocalLow\Xobermon, LLC\Noble Fates\Mods\NobleFates-AdvancedBarracks`

**Comment by oskurd** [comment]
thanks this helped. I was wondering, how difficult it would be to create mod which show damage as floating numbers? If it would be something you could work with some point if interest and time
